version: '3'
services:
  go_db:
    container_name: go_db
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - 5432:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data

  streaming-daemon:
    container_name: streaming-daemon
    image: golang/1.21-bullseye
    build: .
    environment:
      DATABASE_URL: "postgres://postgres:postgres@go_db/postgres?sslmode=disable"
    ports:
      - "8082:8082"
    volumes:
      - app_data:/app/audio
    depends_on:
      - go_db

volumes:
  postgres_data: {}
  app_data: