version: '3'

services:
  dynamodb:
    image: amazon/dynamodb-local
    ports:
      - "8000:8000"
    command: ["-jar", "DynamoDBLocal.jar", "-sharedDb"]

  web:
    build: ./web
    ports:
      - "5000:5000"
    depends_on:
      - dynamodb
    environment:
      - DYNAMODB_HOST=dynamodb
      - DYNAMODB_PORT=8000
